# Database Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/financial
    username: root
    password: 

# Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect